/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservacionvuelos;

/**
 *
 * @author equipo
 */
// proporciona la capacidad de formatear y analizar fechas.
import java.text.SimpleDateFormat;
//se utiliza para representar y manipular fechas.
import java.util.Date;

public class FormularioVentaBoletos extends javax.swing.JFrame {

        /**
         * Creates new form VentaBoletos
         */
        public FormularioVentaBoletos() {
                initComponents();
                // Se configuran tres barras de progreso para que muestren una cadena en la
                // barra de progreso.
                barraDestino1.setStringPainted(true);
                barraDestino2.setStringPainted(true);
                barraDestino3.setStringPainted(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                barraDestino1 = new javax.swing.JProgressBar();
                barraDestino2 = new javax.swing.JProgressBar();
                barraDestino3 = new javax.swing.JProgressBar();
                lbDestino1 = new javax.swing.JLabel();
                lbDestino2 = new javax.swing.JLabel();
                lbDestino3 = new javax.swing.JLabel();
                lbInstruccion1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                lbInstruccion2 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtInfoVentas = new javax.swing.JTextArea();
                jLabel6 = new javax.swing.JLabel();
                btnIniciar = new javax.swing.JButton();
                btnMostrar = new javax.swing.JButton();
                btnSalir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Simulador de ventas");

                lbDestino1.setText("Destino 1: Cd. México a Los Ángeles.");

                lbDestino2.setText("Destino 2: Cd. México a Madrid.");

                lbDestino3.setText("Destino 3: Cd. México a Bogotá.");

                lbInstruccion1.setText("1. Progreso de venta de boletos");

                lbInstruccion2.setText("2. Simular ventas");

                txtInfoVentas.setColumns(20);
                txtInfoVentas.setRows(5);
                jScrollPane1.setViewportView(txtInfoVentas);

                jLabel6.setText("Info ventas");

                btnIniciar.setText("Iniciar");
                btnIniciar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnIniciarActionPerformed(evt);
                        }
                });

                btnMostrar.setText("Mostrar");
                btnMostrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMostrarActionPerformed(evt);
                        }
                });

                btnSalir.setText("Salir");
                btnSalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(lbInstruccion2)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jSeparator2))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jScrollPane1)
                                                                                                                .addComponent(jLabel6))
                                                                                                .addGap(46, 46, 46)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(btnIniciar)
                                                                                                                .addComponent(btnMostrar)
                                                                                                                .addComponent(btnSalir)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lbInstruccion1)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jSeparator1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                265,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(lbDestino1)
                                                                                                                                                .addComponent(lbDestino2)
                                                                                                                                                .addComponent(lbDestino3))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(barraDestino2,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                296,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(barraDestino1,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(barraDestino3,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))))
                                                                                                .addGap(0, 155, Short.MAX_VALUE)))
                                                                .addGap(46, 46, 46)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(lbInstruccion1)
                                                                                .addComponent(jSeparator1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                10,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(barraDestino1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lbDestino1))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbDestino2)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(4, 4, 4)
                                                                                                .addComponent(barraDestino2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(barraDestino3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lbDestino3))
                                                                .addGap(30, 30, 30)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(lbInstruccion2)
                                                                                .addComponent(jSeparator2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                10,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel6)
                                                                                                .addGap(3, 3, 3)
                                                                                                .addComponent(jScrollPane1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnIniciar)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnMostrar)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnSalir)))
                                                                .addContainerGap(32, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // 1. Iniciar simulacion de ventas con los hilos
        private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {
                // Crear instancias de la clase VentaBoletos para cada destino
                VentaBoletos hiloDestino1 = new VentaBoletos("Destino 1", 186, 5500, barraDestino1);
                VentaBoletos hiloDestino2 = new VentaBoletos("Destino 2", 144, 11300, barraDestino2);
                VentaBoletos hiloDestino3 = new VentaBoletos("Destino 3", 190, 7600, barraDestino3);
                // Iniciar los hilos para simular la venta concurrente de boletos en paralelo
                // para los tres destinos.
                new Thread(hiloDestino1).start();
                new Thread(hiloDestino2).start();
                new Thread(hiloDestino3).start();
        }

        // 2. Mostrar la información sobre las ventas en el área de texto
        private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {
                // Obtener la fecha y la hora actual del sistema
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String fechaActual = dateFormat.format(new Date());
                // recupera el valor de cada barra de destino, de acuerdo al porcentaje
                int boletosVendidos1 = barraDestino1.getValue();
                int boletosVendidos2 = barraDestino2.getValue();
                int boletosVendidos3 = barraDestino3.getValue();
                // venta total = ((boletosvendidos*cantidad asientos)/100)*valor boleto)
                int totalVentas1 = (((boletosVendidos1 * 186) / 100) * 5500);
                int totalVentas2 = (((boletosVendidos2 * 144) / 100) * 11300);
                int totalVentas3 = (((boletosVendidos3 * 190) / 100) * 7600);
                // Imprime el resultado en el área de texto
                String resultado = "Fecha actual del sistema: " + fechaActual + "\n\n" +
                                "Destino 1: Porcentaje de boletos vendidos: " + boletosVendidos1 +
                                "% , Total en pesos: $" + totalVentas1 + "\n" +
                                "Destino 2: Porcentaje de boletos vendidos: " + boletosVendidos2 +
                                "% , Total en pesos: $" + totalVentas2 + "\n" +
                                "Destino 3: Porcentaje de boletos vendidos: " + boletosVendidos3 +
                                "% , Total en pesos: $" + totalVentas3;

                txtInfoVentas.setText(resultado);
        }

        // . Salir
        private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
                this.dispose();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FormularioVentaBoletos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FormularioVentaBoletos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FormularioVentaBoletos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FormularioVentaBoletos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FormularioVentaBoletos().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JProgressBar barraDestino1;
        private javax.swing.JProgressBar barraDestino2;
        private javax.swing.JProgressBar barraDestino3;
        private javax.swing.JButton btnIniciar;
        private javax.swing.JButton btnMostrar;
        private javax.swing.JButton btnSalir;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lbDestino1;
        private javax.swing.JLabel lbDestino2;
        private javax.swing.JLabel lbDestino3;
        private javax.swing.JLabel lbInstruccion1;
        private javax.swing.JLabel lbInstruccion2;
        private javax.swing.JTextArea txtInfoVentas;
        // End of variables declaration//GEN-END:variables
}
